### PR TITLE
fix user access issue

### PR DESCRIPTION
**Pull request by ahmadiq**

### CODE REVIEW

**Comment by stakater-user** [comment]
@ahmadiq Image is available for testing. `docker pull docker.io/stakater/git-cloner:SNAPSHOT-PR-2-1`

**Comment by stakater-user** [comment]
@ahmadiq Image is available for testing. `docker pull docker.io/stakater/git-cloner:SNAPSHOT-PR-2-2`

**Comment by stakater-user** [comment]
@ahmadiq Image is available for testing. `docker pull docker.io/stakater/git-cloner:SNAPSHOT-PR-2-3`

**Comment by stakater-user** [comment]
@ahmadiq Image is available for testing. `docker pull docker.io/stakater/git-cloner:SNAPSHOT-PR-2-4`

**Comment by stakater-user** [comment]
@ahmadiq Image is available for testing. `docker pull docker.io/stakater/git-cloner:SNAPSHOT-PR-2-5`

**Review by waseem-h — APPROVED** [review]

**Review by ahsan-storm — COMMENTED** [review]
approved

**Pull request merged**
